language: node_js
dist: trusty
node_js:
  - 10.9.0
cache:
  yarn: true
  directories:
    - "./node_modules"
addons:
  ssh_known_hosts: mralexandernickel.com
before_script:
  - yarn build frontend-subjects
  - yarn build --prod
script:
  - yarn lint
  - yarn test frontend-subjects --watch=false --code-coverage
after_success:
  - cat ./coverage/lcov.info | ./node_modules/.bin/coveralls
before_deploy:
  - openssl aes-256-cbc -K $encrypted_95320be81f38_key -iv $encrypted_95320be81f38_iv
    -in id_ed25519.enc -out /tmp/id_ed25519 -d
  - eval "$(ssh-agent -s)"
  - chmod 600 /tmp/id_ed25519
  - ssh-add /tmp/id_ed25519
deploy:
  provider: script
  skip_cleanup: true
  script: rsync -r --delete-after --quiet $TRAVIS_BUILD_DIR/dist/frontend-subjects-demo/* travis@mralexandernickel.com:/var/www/frontend-subjects-demo
  on:
    branch: master
# deploy:
#   provider: pages
#   skip-cleanup: true
#   github-token: "$GITHUB_TOKEN"
#   keep-history: true
#   local-dir: dist/frontend-subjects-demo
#   on:
#     branch: master
